info_type_mapping = {
    "general_academic": "General Knowledge/Academic",
    "univ_wide": "University Wide",
    "campus_wide": "Campus Wide (Alangilan)",
    "dept": "Academic Departments",
    "program": "Academic Programs",
    "offices": "Offices"
}

office_mapping = {
    "chancellor": "Office of the Chancellor",
    "vice_de": "Vice Chancellor for Development and External Affairs",
    "vice_aa": "Vice Chancellor for Academic Affairs",
    "vice_fa": "Vice Chancellor for Financial Affairs",
    "coe": "College of Engineering",
    "cafad": "College of Architecture, Fine Arts and Design",
    "cet": "College of Engineering Technology",
    "cics": "College of Informatics and Computing Sciences",
    "dept_me": "Mechanical Engineering Department",
    "dept_ce": "Civil Engineering Department",
    "dept_cpe": "Computer Engineering Department",
    "dept_ee": "Electrical Engineering Department",
    "dept_ece": "Electronics Engineering Department",
    "dept_ie": "Industrial Engineering Department",
    "dept_che": "Chemical Engineering Department",
    "dept_mexe": "Mechatronics Engineering Department",
    "dept_ice": "Instrumentation and Control Engineering Department",
    "dept_pete": "Petroleum Engineering Department",
    "dept_se": "Sanitary Engineering Department",
    "dept_arch": "Achitecture Program",
    "dept_id": "Interior Design Program",
    "dept_cs": "Computer Science Program",
    "dept_it": "Information Technology Program",
    "center_steer": "STEER Hub (Science, Technology, Engineering, and Environment Research Hub)",
    "center_likha": "Likha FabLab (Manufacturing Research Center)",
    "center_mtcc": "Material Testing and Calibration Center (MTCC)",
    "center_cti": "Center for Technopreneurship and Innovation (CTI)",
    "center_esrc": "Electronics Systems Research Center (ESRC)",
    "center_gis": "GIS Application Development Center",
    "center_dtc": "Digital Transformation Center (DTC)",
    "center_kist": "Knowledge, Innovation, Science and Technology (KIST) Park",
    "office_reg": "Registrar's Office",
    "office_tao": "Testing and Admission Office (TAO)",
    "office_hrmo": "Human Resource Management Office (HRMO)",
    "office_acct": "Accounting Office",
    "office_assess": "Assessment Office",
    "office_cashier": "Cashier Office",
    "office_ojt": "On-the-Job Training (OJT) Office",
    "office_jpo": "Job Placement Office (JPO)",
    "office_eao": "External Affairs Office",
    "office_eso": "Extension Services Office",
    "office_health": "Health Services Office (Campus Clinic)",
    "office_guidance": "Guidance and Counseling Office",
    "office_discipline": "Office of Student Discipline (OSD)",
    "office_stuaff": "Office of Student Affairs (OSA)",
    "office_sports": "Office of Sports Development Program",
    "office_maintenance": "Building Equipment & Grounds Maintenance",
    "office_bac": "Procurement / BAC Secretariat",
    "office_ssc": "Supreme Student Council (SSC)",
    "office_gym": "Sparta Gymnasium",
    "office_security": "Security / Guard House"
}

target_mapping = {
    "public": "For Public",
    "students": "For Students",
    "faculty": "For Faculty",
    "staff": "For Staff",
    "external": "For External Entities"
}