info_type_mapping = {
    "general_academic": "General Knowledge/Academic",
    "univ_wide": "University Wide",
    "campus_wide": "Campus Wide (Alangilan)",
    "dept": "Academic Departments",
    "program": "Academic Programs",
    "offices": "Offices"
}

office_mapping = {
    "chancellor": "Office of the Chancellor",
    "vice_de": "Vice Chancellor for Development and External Affairs",
    "vice_aa": "Vice Chancellor for Academic Affairs",
    "vice_fa": "Vice Chancellor for Financial Affairs",
    "coe": "College of Engineering",
    "cafad": "College of Architecture, Fine Arts and Design",
    "cet": "College of Engineering Technology",
    "cics": "College of Informatics and Computing Sciences",
    "dept_me": "Mechanical Engineering Department",
    "dept_ce": "Civil Engineering Department",
    "dept_cpe": "Computer Engineering Department",
    "dept_ee": "Electrical Engineering Department",
    "dept_ece": "Electronics Engineering Department",
    "dept_ie": "Industrial Engineering Department",
    "dept_che": "Chemical Engineering Department",
    "dept_mexe": "Mechatronics Engineering Department",
    "dept_ice": "Instrumentation and Control Engineering Department",
    "dept_pete": "Petroleum Engineering Department",
    "dept_se": "Sanitary Engineering Department",
    "prog_arch": "Bachelor of Science in Architecture",
    "prog_id": "Bachelor of Science in Interior Design",
    "prog_cs": "Bachelor of Science in Computer Science",
    "prog_it": "Bachelor of Science in Information Technology",
    "prog_ce": "Bachelor of Science in Civil Engineering",
    "prog_se": "Bachelor of Science in Sanitary Engineering",
    "prog_gde": "Bachelor of Science in Geodetic Engineering",
    "prog_gee": "Bachelor of Science in Geological Engineering",
    "prog_tre": "Bachelor of Science in Transportation Engineering",
    "prog_cere": "Bachelor of Science in Ceramics Engineering",
    "prog_che": "Bachelor of Science in Chemical Engineering",
    "prog_mete": "Bachelor of Science in Metallurgical Engineering",
    "prog_ee": "Bachelor of Science in Electrical Engineering",
    "prog_cpe": "Bachelor of Science in Computer Engineering",
    "prog_ece": "Bachelor of Science in Electronics Engineering",
    "prog_re": "Bachelor of Science in Robotics Engineering",
    "prog_mexe": "Bachelor of Science in Mechatronics Engineering",
    "prog_ice": "Bachelor of Science in Instrumentation and Control Engineering",
    "prog_ie": "Bachelor of Science in Industrial Engineering",
    "prog_me": "Bachelor of Science in Mechanical Engineering",
    "prog_pete": "Bachelor of Science in Petroleum Engineering",
    "prog_name": "Bachelor of Science in Naval Architecture and Marine Engineering",
    "prog_autet": "Bachelor of Automotive Engineering Technology",
    "prog_cet": "Bachelor of Civil Engineering Technology",
    "prog_det": "Bachelor of Drafting Engineering Technology",
    "prog_fet": "Bachelor of Food Engineering Technology",
    "prog_icet": "Bachelor of Instrumentation and Control Engineering Technology",
    "prog_met": "Bachelor of Mechanical Engineering Technology",
    "prog_mexet": "Bachelor of Mechatronics Engineering Technology",
    "prog_wfet": "Bachelor of Welding and Fabrication Engineering Technology",
    "prog_viscom": "Bachelor of Fine Arts and Design major in Visual Communication",
    "center_steer": "STEER Hub (Science, Technology, Engineering, and Environment Research Hub)",
    "center_likha": "Likha FabLab (Manufacturing Research Center)",
    "center_mtcc": "Material Testing and Calibration Center (MTCC)",
    "center_cti": "Center for Technopreneurship and Innovation (CTI)",
    "center_esrc": "Electronics Systems Research Center (ESRC)",
    "center_gis": "GIS Application Development Center",
    "center_dtc": "Digital Transformation Center (DTC)",
    "center_kist": "Knowledge, Innovation, Science and Technology (KIST) Park",
    "office_reg": "Registrar's Office",
    "office_tao": "Testing and Admission Office (TAO)",
    "office_hrmo": "Human Resource Management Office (HRMO)",
    "office_acct": "Accounting Office",
    "office_assess": "Assessment Office",
    "office_cashier": "Cashier Office",
    "office_ojt": "On-the-Job Training (OJT) Office",
    "office_jpo": "Job Placement Office (JPO)",
    "office_eao": "External Affairs Office",
    "office_eso": "Extension Services Office",
    "office_health": "Health Services Office (Campus Clinic)",
    "office_guidance": "Guidance and Counseling Office",
    "office_discipline": "Office of Student Discipline (OSD)",
    "office_stuaff": "Office of Student Affairs (OSA)",
    "office_sports": "Office of Sports Development Program",
    "office_maintenance": "Building Equipment & Grounds Maintenance",
    "office_bac": "Procurement / BAC Secretariat",
    "office_ssc": "Supreme Student Council (SSC)",
    "office_gym": "Sparta Gymnasium",
    "office_security": "Security / Guard House"
}

target_mapping = {
    "public": "For Public",
    "students": "For Students",
    "faculty": "For Faculty",
    "staff": "For Staff",
    "external": "For External Entities"
}